# Generated by Django 2.2.5 on 2020-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0002_auto_20201229_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Chevy', 'Chevy'), ('Subaru', 'Subaru'), ('Mercedes-benz', 'Mercedes-benz'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], default='', max_length=6),
        ),
    ]
