# Generated by Django 2.2.5 on 2020-12-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0004_auto_20201229_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('1995', '1995'), ('2015', '2015'), ('2000', '2000'), ('2005', '2005'), ('1990', '1990'), ('2010', '2010')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Subaru', 'Subaru'), ('Honda', 'Honda'), ('Chevy', 'Chevy'), ('Mercedes-benz', 'Mercedes-benz'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='', max_length=6),
        ),
    ]
