# Generated by Django 2.2.5 on 2021-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0006_auto_20210102_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Honda', 'Honda'), ('Subaru', 'Subaru'), ('Mercedes-benz', 'Mercedes-benz'), ('Chevy', 'Chevy'), ('Toyota', 'Toyota')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('1995', '1995'), ('2005', '2005'), ('2020', '2020'), ('2000', '2000'), ('1990', '1990'), ('2015', '2015'), ('2010', '2010')], default='', max_length=6),
        ),
    ]
