# Generated by Django 2.2.5 on 2021-01-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0007_auto_20210102_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Chevy', 'Chevy'), ('Subaru', 'Subaru'), ('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Mercedes-benz', 'Mercedes-benz')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('2005', '2005'), ('1995', '1995'), ('2015', '2015'), ('1990', '1990'), ('2000', '2000'), ('2010', '2010'), ('2020', '2020')], default='', max_length=6),
        ),
    ]
