# Generated by Django 2.2.5 on 2021-01-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0008_auto_20210102_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Subaru', 'Subaru'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Mercedes-benz', 'Mercedes-benz'), ('Chevy', 'Chevy')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('1990', '1990'), ('2015', '2015'), ('2005', '2005'), ('2000', '2000'), ('2020', '2020'), ('1995', '1995'), ('2010', '2010')], default='', max_length=6),
        ),
    ]
