# Generated by Django 2.2.5 on 2021-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0009_auto_20210102_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Chevy', 'Chevy'), ('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Mercedes-benz', 'Mercedes-benz'), ('Subaru', 'Subaru')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2010', '2010'), ('2015', '2015'), ('1990', '1990'), ('2005', '2005'), ('1995', '1995'), ('2000', '2000')], default='', max_length=6),
        ),
    ]
