# Generated by Django 2.2.5 on 2021-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPartsApp', '0010_auto_20210103_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycarparts',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Subaru', 'Subaru'), ('Mercedes-benz', 'Mercedes-benz'), ('Chevy', 'Chevy'), ('Ford', 'Ford')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='mycarparts',
            name='year',
            field=models.CharField(choices=[('1990', '1990'), ('2015', '2015'), ('2000', '2000'), ('2005', '2005'), ('1995', '1995'), ('2010', '2010'), ('2020', '2020')], default='', max_length=6),
        ),
    ]
